handy-candy/HandyCandy_Server

.eslintrc.js
.eslintrc.json
.gitignore
.prettierrc.json
commitlint.config.js
package-lock.json
package.json

혹시나 각자의 vscode에 settings.json에 설정이 안 되어 있다면 설정해주세욥~
```json
{
"editor.formatOnSave": true, 
"[javascript]": { "editor.formatOnSave": true }, 
"editor.codeActionsOnSave": { 
"source.fixAll.eslint": true
},
"[json]": {
"editor.quickSuggestions": {
"strings": true
},
"editor.suggest.insertMode": "replace",
},
"typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib",
"explorer.confirmDelete": false,
"window.zoomLevel": 0,
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.formatOnType": true,
"launch": {
"configurations": [],
"compounds": []
},
"json.schemas": [
]
}
```
참고 링크 : [prettier & eslint 설정](https://overcome-the-limits.tistory.com/entry/%ED%98%91%EC%97%85-ESLint-Prettier-Airbnb-Style-Guide%EB%A1%9C-%EC%BD%94%EB%93%9C-%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%9 …

chore: eslint 및 prettier 설정

---

src/interfaces/ICandy.ts
src/interfaces/ICategory.ts
src/interfaces/IReview.ts
src/interfaces/IUser.ts
src/models/Candy.ts
src/models/Category.ts
src/models/Review.ts
src/models/User.ts

User id부분을 제외한 다른 부분 다 수정완료했습니다~!

feat: DB 환경 세팅

---

src/middleware/auth.ts

feat: 미들웨어에 auth 추가

---

src/api/Candies.ts
src/index.ts

feat: 기다리는 캔디 정보 전송 구현

---

src/api/Candies.ts
src/index.ts

feat: 캔디 삭제 및 추천캔디 구현

---

src/api/Candies.ts
src/index.ts

feat: 캔디 추가하기 기능구현

---

src/api/candies.ts
src/index.ts

feat: 월별 완료한 캔디 정보전송 구현

---

src/api/candies.ts
src/index.ts

feat: 완료캔디 수정기능 구현

---

src/api/candies.ts
src/index.ts

feat: 리뷰 등록 기능구현

---

src/api/candies.ts
src/index.ts

feat: 완료캔디 상세페이지 기능구현

---

src/api/candies.ts
src/index.ts

feat: 담은 캔디 수정 기능구현

---

src/api/candies.ts
src/index.ts

feat: 캔디 이미지 수정기능 구현

---

src/api/candies.ts
src/index.ts

chore: conflict solved

---

src/api/candies.ts
src/models/Category.ts

chore: 캔디 추가 시 상세정보 받기

---

src/api/userInfo.ts

chore: 유저정보 response 수정

---

src/api/candies.ts

chore: 캔디 추가 시 보상날짜 자동생성

---

src/api/userInfo.ts

chore: userInfo res 수정

---

src/api/candies.ts
src/api/userInfo.ts

chore: 앱잼용 데이터로 세팅

---

src/api/category.ts

chore: eslint 적용

---

src/api/candies.ts

chore: 완료캔디 상단 이미지 수정

---

src/api/candy.ts
src/api/category.ts

feat: 배너 추가 (#83)

---

package-lock.json
package.json
src/index.ts

chore: CORS 허용

---

src/index.ts

chore: index.ts파일 수정

---

src/api/candies.ts
src/controllers/candies.ts
src/dto/candies.dto/index.ts
src/services/CandiesService.ts
src/services/SearchService.ts

fix: res 수정

---

src/api/candy.ts
src/api/category.ts
src/controllers/candy.ts
src/controllers/category.ts
src/controllers/index.ts
src/dto/category.dto/index.ts
src/services/CandyService.ts
src/services/CategoryService.ts
src/services/index.ts

chore: category, candy DTO 적용
